apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regcred
      containers:
      - name: auth
        image: deeaxfun2/auth:latest
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /api/v1/check_api
            port: 8001  # Changed from 80 to 8001
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: RECIPE_SERVICE_HOST_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: recipe
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: jwt-secret
        - name: ALGORITHM
          value: "HS256"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30" 
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-host
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password