apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: eu-stockholm-1.ocir.io/axyklytnjcih/recipe-repo/gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_SERVICE_HOST_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: auth
        - name: RECIPE_SERVICE_HOST_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: recipe
        - name: INGREDIENT_SERVICE_HOST_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: ingredient
        - name: MEALPLAN_SERVICE_HOST_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: meal
        - name: RATING_SERVICE_HOST_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: rating
        - name: NOTIFICATION_SERVICE_HOST_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: notification
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: jwt-secret
        - name: ALGORITHM
          value: "HS256"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30" 
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-host
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password