apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: psudomic/gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: AUTH_SERVICE_HOST_URL
          value: "http://127.0.0.1:53268/api/v1"  # Simplified service URL
        - name: RECIPE_SERVICE_HOST_URL
          value: "http://127.0.0.1:53284/api/v1"
        - name: INGREDIENT_SERVICE_HOST_URL
          value: "http://127.0.0.1:53274/api/v1"
        - name: MEALPLAN_SERVICE_HOST_URL
          value: "http://127.0.0.1:53278/api/v1"
        - name: RATING_SERVICE_HOST_URL
          value: "http://127.0.0.1:53282/api/v1"
        - name: NOTIFICATION_SERVICE_HOST_URL
          value: "http://127.0.0.1:53280"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: jwt-secret
        - name: ALGORITHM
          value: "HS256"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "30" 
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: MYSQL_HOST
          value: "127.0.0.1:53270"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password