apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: psudomic/notification:latest
        ports:
        - containerPort: 8004
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: SMTP_SERVER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: smtp-host
        - name: SMTP_PORT
          value: "465"
        - name: SENDER_EMAIL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: sender-email
        - name: SENDER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: sender-password
        - name: MYSQL_HOST
          value: "127.0.0.1:53270"  # MySQL service name
        - name: MYSQL_PORT
          value: "3306"        # MySQL default port
        - name: MYSQL_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: database-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
