apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8006"
spec:
  selector:
    app: recipe
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8006
  type: ClusterIP